apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
provisioner: {{ .Values.storageClassName }}
# TODO: check what it does
volumeBindingMode: Immediate
reclaimPolicy: Delete
