apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClassName }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
provisioner: {{ .Values.storageClassName }}
volumeBindingMode: Immediate
reclaimPolicy: Delete
