apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-rclone-example
  annotations:
    csi-rclone.dev/secretName: csi-rclone-test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: tasko-csi-rclone-secret-annotation
---
apiVersion: v1
kind: Secret
metadata:
  name: csi-rclone-test
type: Opaque
stringData:
  remote: giab
  remotePath: giab/
  configData: |
    [giab]
    type = s3
    provider = AWS
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test
      image: debian
      volumeMounts:
        - mountPath: "/giab"
          name: task-pv-storage
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: csi-rclone-example
