apiVersion: v1
kind: Pod
metadata:
    name: nginx-example
    namespace: csi-rclone-example-2
    labels:
        run: nginx-example
spec:
    containers:
        - image: nginx
          imagePullPolicy: Always
          name: nginx-example
          ports:
              - containerPort: 80
                protocol: TCP
          volumeMounts:
              - mountPath: /usr/share/nginx/html
                name: data-rclone-example
    volumes:
        - name: data-rclone-example
          persistentVolumeClaim:
              claimName: csi-rclone-example-2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: csi-rclone-example-2
    namespace: csi-rclone-example-2
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 10Gi
    storageClassName: csi-rclone
---
apiVersion: v1
kind: Secret
metadata:
  name: csi-rclone-example-2
  namespace: csi-rclone-example-2
type: Opaque
stringData:
  remote: giab
  remotePath: giab/
  configData: |
    [giab]
    type = s3
    provider = AWS
