name: Build dev version

on:
  push:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CHART_NAME: ${{ github.repository }}/helm-chart

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-image:
    runs-on: ubuntu-24.04
    outputs:
      image: ${{ steps.docker_image.outputs.image }}
      image_repository: ${{ steps.docker_image.outputs.image_repository }}
      image_tag: ${{ steps.docker_image.outputs.image_tag }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install chartpress
        run: pip install chartpress
      - name: Get image tag from chartpress
        id: chartpress
        run: |
          CHARTPRESS_TAG=$(chartpress --list-images | head -n1 | cut -d":" -f2)
          echo "CHARTPRESS_TAG=${CHARTPRESS_TAG}"
          echo "chartpress_tag=${CHARTPRESS_TAG}" >> "$GITHUB_OUTPUT"
      - name: Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.chartpress.outputs.chartpress_tag }}
            type=sha
      - name: Extract Docker image name
        id: docker_image
        run: |
          IMAGE=$(echo '${{ steps.meta.outputs.json }}' | jq -cr '.tags[0]')
          IMAGE_REPOSITORY=$(echo "$IMAGE" | cut -d":" -f1)
          IMAGE_TAG=$(echo "$IMAGE" | cut -d":" -f2)
          echo "image=$IMAGE" >> "$GITHUB_OUTPUT"
          echo "image_repository=$IMAGE_REPOSITORY" >> "$GITHUB_OUTPUT"
          echo "image_tag=$IMAGE_TAG" >> "$GITHUB_OUTPUT"
      # - name: Set up Docker buildx
      #   uses: docker/setup-buildx-action@v3
      # - name: Set up Docker
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
      #     cache-from: type=registry,ref=${{ steps.docker_image.outputs.image_repository }}:buildcache
      #     cache-to: type=registry,ref=${{ steps.docker_image.outputs.image_repository }}:buildcache,mode=max

  publish-chart:
    needs: [build-image]
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Setup Helm
        uses: azure/setup-helm@v4
      - name: Install chartpress
        run: pip install chartpress
      - name: Setup Helm push
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin
      
