name: Publish chart
on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:
jobs:
  publish-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - uses: azure/setup-helm@v3
        with:
          token: ${{secrets.GITHUB_TOKEN }}
      - name: install dependencies
        run: pip install chartpress
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Flake check
        run: nix flake check
      - name: Publish images
        uses: workflow/nix-shell-action@v3.3.0
        env:
          DOCKER_USERNAME: ${{ secrets.RENKU_DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.RENKU_DOCKER_PASSWORD }}
        with:
          flakes-from-devshell: true
          flakes: .#csi-rclone-container-layerd
          script: |
            export TAG=$(echo ${GITHUB_REF} |cut -d/ -f3)

            nix build .#csi-rclone-container-layerd-aarch64 && ./result | docker load
            docker tag csi-rclone:latest renku/csi-rclone:latest-aarch64
            docker tag csi-rclone:latest renku/csi-rclone:${TAG}-aarch64
            
            nix build .#csi-rclone-container-layerd-amd64 && ./result | docker load
            docker tag csi-rclone:latest renku/csi-rclone:latest-amd64
            docker tag csi-rclone:latest renku/csi-rclone:${TAG}-amd64
            
            echo ${DOCKER_PASSWORD}|docker login -u ${DOCKER_USERNAME} --password-stdin

            docker push renku/csi-rclone:latest-aarch64
            docker push renku/csi-rclone:${TAG}-aarch64
            docker push renku/csi-rclone:latest-amd64
            docker push renku/csi-rclone:${TAG}-amd64

            docker manifest create \
              renku/csi-rclone:${TAG} \
              --amend renku/csi-rclone:${TAG}-amd64 \
              --amend renku/csi-rclone:${TAG}-aarch64
      - name: Publish chart
        env:
          GITHUB_TOKEN: ${{ secrets.RENKUBOT_GITHUB_TOKEN }}
        run: |
          cd deploy
          git config --global user.email "renku@datascience.ch"
          git config --global user.name "Renku Bot"
          export TAG=$(echo ${GITHUB_REF} |cut -d/ -f3)
          helm dep update csi-rclone
          chartpress --tag $TAG
          helm lint csi-rclone
          chartpress --tag $TAG --no-build --publish-chart
          
